### ISSUE TITLE
Updates on making this into a cli?

### ISSUE THREAD

**Issue by brasilikum** [jfmengels/elm-lint#1]

**Comment by jfmengels** [comment]
The underlying parser for this plugin has improved a lot, making this tool potentially usable. Now that that is the case, I'll be more motivated to work on this, and I'll resume work on a CLI that I started months ago soon-ish :)

**Comment by jfmengels** [comment]
There is one now :)
Check the README on how to get and use it.
I will try to make a blog post about it soon to better announce it.
